// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/windurisky/hometest-dagangan/domain"
)

// FareConfigurationRepository is an autogenerated mock type for the FareConfigurationRepository type
type FareConfigurationRepository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: _a0
func (_m *FareConfigurationRepository) GetAll(_a0 string) ([]domain.FareConfiguration, error) {
	ret := _m.Called(_a0)

	var r0 []domain.FareConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.FareConfiguration, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.FareConfiguration); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FareConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFareConfigurationRepository creates a new instance of FareConfigurationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFareConfigurationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FareConfigurationRepository {
	mock := &FareConfigurationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
