// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/windurisky/hometest-dagangan/domain"
)

// FareConfigurationUsecase is an autogenerated mock type for the FareConfigurationUsecase type
type FareConfigurationUsecase struct {
	mock.Mock
}

// FindByMileage provides a mock function with given fields: _a0
func (_m *FareConfigurationUsecase) FindByMileage(_a0 uint64) (domain.FareConfiguration, error) {
	ret := _m.Called(_a0)

	var r0 domain.FareConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (domain.FareConfiguration, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uint64) domain.FareConfiguration); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.FareConfiguration)
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFareConfigurationUsecase creates a new instance of FareConfigurationUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFareConfigurationUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *FareConfigurationUsecase {
	mock := &FareConfigurationUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
